
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "batman",
    "email": "kushagra.agarwal.2709@gmail.com",
    "password": "pass1234"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "daksheshgupta4@gmail.com",
    "password": "Dakshesh"
}

###

GET http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1c2guYWdhcndhbC4wMTJAZ21haWwuY29tIiwiaWF0IjoxNzIwNTA3NTA2LCJleHAiOjE3MjExMTIzMDZ9.mXulad_guo7ZCZPhIoeTo2ycbQ625tL1mNwvUEpe3Y4"
}

###

POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1c2guYWdhcndhbC4wMTJAZ21haWwuY29tIiwiaWF0IjoxNzIwNTA4NDAxLCJleHAiOjE3MjA1MDkzMDF9.1MWbaMhSRbuOErhxkv9BiyIlN2sKVzTJJrHvDv5aaiY

{
    "refreshToken": "lol.eyJlbWFpbCI6Imt1c2guYWdhcndhbC4wMTJAZ21haWwuY29tIiwiaWF0IjoxNzIwNTA4NDAxLCJleHAiOjE3MjExMTMyMDF9.K4cDpVFyuYnAa3xtCmXeS1sq49joTg8lNoJk_u-asJk"
}

###

GET http://localhost:3000/api/auth/google
Content-Type: application/json

###

POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
    "email": "kushagra.agarwal.2709@gmail.com"
}

###

POST http://localhost:3000/api/auth/set-password-otp 
Content-Type: application/json

{
    "email": "kushagra.agarwal.2709@gmail.com",
    "otp": 794864,
    "newPassword": "Noicee"
}

###

GET http://localhost:3000/api/auth/verify-email/:token
Content-Type: application/json

###

GET http://localhost:3000/api/auth/test
Content-Type: application/json
Authorization: Bearer .eyJlbWFpbCI6Imt1c2guYWdhcndhbC4wMTJAZ21haWwuY29tIiwiaWF0IjoxNzIwNTU4NTg1LCJleHAiOjE3MjA1NTk0ODV9.nX0oZJTlBGugFw01z5DbYY-KurnU_SEgw82wMTU1qm8


###

GET http://localhost:3000/api/auth/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt1c2hhZ3JhLmFnYXJ3YWwuMjcwOUBnbWFpbC5jb20iLCJpYXQiOjE3MjA2MzgzMjN9.1D1FzOSJUHNPVtrs472yS4aIwUwjqddopSaTSLGamCI